### ISSUE TITLE
Start using of Lombok

### ISSUE THREAD

**Issue by driversti** [DanielW1987/metal-release-radar#107]
https://github.com/DanielW1987/metal-release-radar/blob/master/src/main/java/com/metalr2/web/controller/rest/ReleasesRestController.java#L33

With Lombok, you can get rid of this redundant block of code by adding **@RequiredArgsConstructor** or **@AllArgsConstructor**.

**Comment by hedgehog1833** [comment]
Hi driversti!
Thanks for your input! We are already using Lombok in some places, not sure why it is not already included here. I'm going to get this straight here too, thanks!
Best regards

**Comment by hedgehog1833** [comment]
Solved with #109
